def PrnJavaScript(filename,lat,lon):
    with open(filename, mode='w') as fp:
        # ---------- HTML header ------------
        fp.write('<!DOCTYPE html>\n')
        fp.write('<html>\n')
        fp.write('   <head>\n')
        fp.write('   <meta name="viewport" content="initial-scale=1.0, user-scalable=no">\n')
        fp.write('   <meta charset="utf-8">\n')
        fp.write('   <title>福岡タワーの影</title>\n')
        fp.write('   <style>\n')
        fp.write('#map {\n')
        fp.write('      height: 100%;\n')
        fp.write('     }\n')
        fp.write('      html, body {\n')
        fp.write('      height: 100%;\n')
        fp.write('      margin: 0;\n')
        fp.write('      padding: 0;\n')
        fp.write('     }\n')
        fp.write('  </style>\n')
        fp.write('</head>\n')
        fp.write('<body>\n')
        fp.write('<div id="map"></div>\n')
        fp.write('<script>\n')
        fp.write('/* Google Maps PrnJavaScript */\n')
        fp.write('function initMap() {\n')
        fp.write('   var map = new google.maps.Map(document.getElementById(\'map\'),{\n')
        fp.write('      zoom: 15,\n')
        fp.write('      center: {lat: '+str(lat[0])+', lng: '+str(lon[0])+'},\n')
        fp.write('      mapTypeID: \'terrain\' \n')
        fp.write('});\n')

        n=len(lat)

        fp.write('var triangleCoords = [\n')
        for i in range(n):
            fp.write('        {lat: '+str(lat[i])+', lng: '+str(lon[i])+'},\n')
        fp.write('        {lat: '+str(lat[0])+', lng: '+str(lon[0])+'}\n')
        fp.write('];\n')
        fp.write('\n')
        fp.write('// Construct the polygon.\n')
        fp.write(' var sunTriangle = new google.maps.Polygon({\n')
        fp.write('    paths: triangleCoords,\n')
        fp.write('    strokeColor: \'#FF0000\',\n')
        fp.write('    strokeOpacity: 0.8,\n')
        fp.write('    strokeWeight: 2,\n')
        fp.write('    fillColor: \'#FF0000\',\n')
        fp.write('    fillOpacity: 0.35\n')
        fp.write('});\n')
        fp.write('sunTriangle.setMap(map);\n')
        fp.write('}\n')
        fp.write('</script>\n')
        fp.write('<script async defer\n')
        fp.write('      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDXxxpAAPkHdujr5Rht0Kl_gDrTtM0q25k&callback=initMap">\n')
        fp.write('</script>\n')
        fp.write('</body>\n')
        fp.write('</html>\n')

